#include "Constants.h"

float offsetX = 0, offsetY = 0;
float startingPositionX = 100, startingPositionY = 180;
int currentLevel = 0;

std::vector<std::string> level1 = {
    "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "0                                                                                                                                                                                                                                                                                                             E       0",
    "0                                                                                    w                                                                                                                                                                                                                        E       0",
    "0                   w                                  w                   w                                                                                                                                                                                                                                  E       0",
    "0                                      w                                       kk                                                                                                                                                                                                                             E       0",
    "0                                                                             k  k    k    k                                                                                                                                                                                                                  E       0",
    "0                      c                                                      k      kkk  kkk  w                                                                                                                                                                                                              E       0",
    "0                                                                       r     k       k    k                                                                                                                                                                                                                  E       0",
    "0                                                                      rr     k  k                                                                                                                                                                                                                            E       0",
    "0                                                                     rrr      kk                                                                                                                                                                                                                             E       0",
    "0               c    kckck                                           rrrr                                                                                                                                                                                                                                     E       0",
    "0                                      t0                           rrrrr                                                                                                                                                                                                                                     E       0",
    "0G                                     00              t0          rrrrrr            G                                                                                                                                                                                                                        E       0",
    "0           d    g       d             00              00         rrrrrrr                                                                                                                                                                                                                                     E       0",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
};
std::vector<std::vector<std::string>> TileMap = { level1 };
/*
    "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "0                                                                                                                                                                                                                                                                                                             E       0",
    "0                                                                                    w                                                                                                                                                                                                                        E       0",
    "0                   w                                  w                   w                                                                                                                                                                                                                                  E       0",
    "0                                      w                                       kk                                                                                                                                                                                                                             E       0",
    "0                                                                             k  k    k    k                                                                                                                                                                                                                  E       0",
    "0                      c                                                      k      kkk  kkk  w                                                                                                                                                                                                              E       0",
    "0                                                                       r     k       k    k                                                                                                                                                                                                                  E       0",
    "0                        asdas                                         rr     k  k                                                                                                                                                                                                                            E       0",
    "0                                      asdas                          rrr      kk                                                                                                                                                                                                                             E       0",
    "0               c    kckck                                           rrrr                                                                                                                                                                                                                                     E       0",
    "0                                      t0                           rrrrr                                                                                                                                                                                                                                     E       0",
    "0G                                     00              t0          rrrrrr            G                                                                                                                                                                                                                        E       0",
    "0           d    g       d             00              00         rrrrrrr                                                                                                                                                                                                                                     E       0",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
};

std::vector<std::vector<std::string>> TileMap = { level2 };
*/
